# Generated by Django 2.0.1 on 2018-01-24 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import neo_importer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('uploaded_file', models.FileField(upload_to=neo_importer.models.content_file_name)),
                ('results', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, choices=[('Enqueued', 'Enqueued'), ('Processing', 'Processing'), ('Processed', 'Processed'), ('Failed', 'Failed')], max_length=16, null=True)),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('start_execution_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('finish_execution_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('notification_sent', models.NullBooleanField(default=False)),
                ('original_filename', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('form_params', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_upload_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
